<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Pso2ShapeStudio.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\App\Pso2ShapeStudio.App.csproj" />
    <ProjectReference Include="..\..\src\Character\Pso2ShapeStudio.Character.csproj" />
    <ProjectReference Include="..\..\src\Formats\Pso2ShapeStudio.Formats.csproj" />
    <ProjectReference Include="..\..\src\Rigging\Pso2ShapeStudio.Rigging.csproj" />
    <ProjectReference Include="..\..\src\GameData\Pso2ShapeStudio.GameData.csproj" />
    <ProjectReference Include="$(AmlRoot)\AquaModelLibrary.Data\AquaModelLibrary.Data.csproj"
                      SetConfiguration="Configuration=$(Configuration)"
                      SetPlatform="Platform=AnyCPU"
                      GlobalPropertiesToRemove="Platform" />
    <ProjectReference Include="$(AmlRoot)\AquaModelLibrary.Helpers\AquaModelLibrary.Helpers.csproj"
                      SetConfiguration="Configuration=$(Configuration)"
                      SetPlatform="Platform=AnyCPU"
                      GlobalPropertiesToRemove="Platform" />
  </ItemGroup>

</Project>
