using System.Globalization;
using Pso2ShapeStudio.GameData;

namespace Pso2ShapeStudio.App.Localization;

public enum AppLanguage
{
    English,
    Korean,
    Japanese,
}

public enum AppText
{
    Subtitle,
    OpenModels,
    GameDataHeader,
    SelectGameFolder,
    RefreshCache,
    DataFolderUnspecified,
    DataFolderHelp,
    SearchPlaceholder,
    Search,
    LoadSelectedModel,
    ShapeSliders,
    LoadCharacter,
    LoadAqm,
    ResetShape,
    SaveAqm,
    CameraHelp,
    Ready,
    Statistics,
    Scale,
    Position,
    Rotation,
    ModelPickerTitle,
    ModelPickerType,
    GameFolderPickerTitle,
    SearchResultCount,
    ModelSearchFailed,
    WearBasewear,
    WearOuterwear,
    WearSetwear,
    WearCostume,
    DataPathValid,
    CacheReadyInline,
    CacheReadyStatus,
    DataPrepareFailedInline,
    DataPrepareFailedStatus,
    CacheUnavailable,
    Refreshing,
    CacheBuildingStatus,
    CacheBuildingInline,
    CacheCompletedInline,
    CacheCreatedStatus,
    CacheFailedInline,
    CacheFailedStatus,
    InvalidKeep,
    Invalid,
    GameFolderFailed,
    RestoreFailed,
    CharacterPickerTitle,
    CharacterPickerType,
    AqmLoadTitle,
    AqmFileType,
    AqmSaveTitle,
    AqmSaved,
    AqmSaveFailed,
    ShapeReset,
    ReadingFiles,
    ModelsCount,
    TexturesCount,
    IceDdsCount,
    IceEntriesCount,
    BonesCount,
    CharacterBonesCount,
    AqmAdjustmentsCount,
    NoLoadableData,
    LoadFailed,
    AqnMissing,
    QualityMissing,
    QualityHigh,
    QualityNormal,
    UnnamedItem,
    RendererReady,
    RendererInitFailed,
    RendererRenderFailed,
    RendererContextLost,
    FailedWord,
    DataPathNotSelected,
    DataPathInvalid,
    DataPathFolderMissing,
    DataPathStructureMissing,
    DataPathFilesMissing,
    DataPathAccessDenied,
    LanguageTip,
    RemoveModel,
    ModelRemoved,
    SkinTextures,
    SkinType1,
    SkinType2,
    SkinLoaded,
    SkinLoadFailed,
    ShapeUndone,
    ShapeRedone,
    BackgroundTip,
    FloorGuide,
    FloorGuideTip,
    BackgroundDark,
    BackgroundGraphite,
    BackgroundGray,
    BackgroundSilver,
    BackgroundWhite,
    BackgroundNavy,
    BackgroundForest,
    BackgroundMagenta,
    Options,
    OptionsTitle,
    General,
    GameDataFolder,
    Browse,
    DefaultSkinColors,
    MainSkinColor,
    SubSkinColor,
    HexColorHelp,
    EditableBones,
    BuiltInGroups,
    CustomGroups,
    BoneEditorHelp,
    AddPair,
    AddSingle,
    Remove,
    Pair,
    Single,
    Kind,
    GroupName,
    LeftBone,
    RightBone,
    BoneName,
    Save,
    Cancel,
    ModelRequiredForBone,
    InvalidSkinColor,
    MissingBoneFields,
    BoneNotFound,
    DuplicateBone,
    OptionsSaved,
}

public static class AppLocalizer
{
    private static readonly IReadOnlyDictionary<AppText, string> English = new Dictionary<AppText, string>
    {
        [AppText.Subtitle] = "Edit PSO2 AQP/AQN models and character shapes",
        [AppText.OpenModels] = "Open model files…",
        [AppText.GameDataHeader] = "Game Data / Model Search",
        [AppText.SelectGameFolder] = "Select game folder…",
        [AppText.RefreshCache] = "Refresh cache",
        [AppText.DataFolderUnspecified] = "Data folder not selected",
        [AppText.DataFolderHelp] = "Select the game installation folder, pso2_bin, or data folder.",
        [AppText.SearchPlaceholder] = "Name · ID · file name · MD5",
        [AppText.Search] = "Search",
        [AppText.LoadSelectedModel] = "Load selected model",
        [AppText.ShapeSliders] = "Shape Sliders · S / P / R",
        [AppText.LoadCharacter] = "Load character file…",
        [AppText.LoadAqm] = "Load _sa.aqm…",
        [AppText.ResetShape] = "Reset shape",
        [AppText.SaveAqm] = "Save _sa.aqm…",
        [AppText.CameraHelp] = "L/R drag: rotate   Ctrl+drag: move vertically   Middle click: reset view   Wheel: zoom",
        [AppText.Ready] = "Ready",
        [AppText.Statistics] = "Models {0:N0} · Vertices {1:N0} · Triangles {2:N0} · Textures {3:N0} · {4:F1} fps",
        [AppText.Scale] = "Scale (S)",
        [AppText.Position] = "Position (P)",
        [AppText.Rotation] = "Rotation (R)",
        [AppText.ModelPickerTitle] = "Open PSO2 model files",
        [AppText.ModelPickerType] = "PSO2 model / skeleton / ICE",
        [AppText.GameFolderPickerTitle] = "Select the PSO2 game installation folder",
        [AppText.SearchResultCount] = "{0:N0} search results",
        [AppText.ModelSearchFailed] = "Model search failed: {0}",
        [AppText.WearBasewear] = "Basewear",
        [AppText.WearOuterwear] = "Outerwear",
        [AppText.WearSetwear] = "Setwear",
        [AppText.WearCostume] = "Costume (classic)",
        [AppText.BackgroundTip] = "Viewport background",
        [AppText.FloorGuide] = "Floor guide",
        [AppText.FloorGuideTip] = "Show the world Y=0 floor guide",
        [AppText.BackgroundDark] = "Dark",
        [AppText.BackgroundGraphite] = "Graphite",
        [AppText.BackgroundGray] = "Gray",
        [AppText.BackgroundSilver] = "Silver",
        [AppText.BackgroundWhite] = "White",
        [AppText.BackgroundNavy] = "Navy",
        [AppText.BackgroundForest] = "Forest",
        [AppText.BackgroundMagenta] = "Magenta",
        [AppText.DataPathValid] = "PSO2 game data path verified.",
        [AppText.CacheReadyInline] = "Game data verified · {0:N0} cached items ready",
        [AppText.CacheReadyStatus] = "Model cache ready: {0:N0} items",
        [AppText.DataPrepareFailedInline] = "The game data path is valid, but settings or cache preparation failed: {0}",
        [AppText.DataPrepareFailedStatus] = "Game data preparation failed: {0}",
        [AppText.CacheUnavailable] = "The cache cannot be refreshed: {0}",
        [AppText.Refreshing] = "Refreshing…",
        [AppText.CacheBuildingStatus] = "Building the CMX model cache…",
        [AppText.CacheBuildingInline] = "Game data verified · refreshing the model cache…",
        [AppText.CacheCompletedInline] = "Game data verified · {0:N0} cached items · {1:F1}s",
        [AppText.CacheCreatedStatus] = "Model cache created: {0:N0} items · {1:F1}s",
        [AppText.CacheFailedInline] = "Game data was verified, but cache refresh failed: {0}",
        [AppText.CacheFailedStatus] = "Model cache creation failed: {0}",
        [AppText.InvalidKeep] = "The selected path is invalid; the existing path was kept: {0}",
        [AppText.Invalid] = "The selected path is invalid: {0}",
        [AppText.GameFolderFailed] = "Game folder setup failed: {0}",
        [AppText.RestoreFailed] = "Saved data folder restore failed: {0}",
        [AppText.CharacterPickerTitle] = "Open a PSO2 character shape file",
        [AppText.CharacterPickerType] = "PSO2 character file",
        [AppText.AqmLoadTitle] = "Open Shape Adjust AQM",
        [AppText.AqmFileType] = "AQM motion",
        [AppText.AqmSaveTitle] = "Save Shape Adjust AQM",
        [AppText.AqmSaved] = "Saved {0} · {1:N0} adjusted bones",
        [AppText.AqmSaveFailed] = "AQM save failed: {0}",
        [AppText.ShapeReset] = "Shape Adjust was reset.",
        [AppText.ReadingFiles] = "Reading files…",
        [AppText.ModelsCount] = "{0:N0} models",
        [AppText.TexturesCount] = "{0:N0} displayed textures",
        [AppText.IceDdsCount] = "{0:N0} ICE DDS files",
        [AppText.IceEntriesCount] = "{0:N0} ICE entries",
        [AppText.BonesCount] = "{0:N0} bones",
        [AppText.CharacterBonesCount] = "{0:N0} character bones",
        [AppText.AqmAdjustmentsCount] = "{0:N0} AQM adjustments",
        [AppText.NoLoadableData] = "No loadable data was found.",
        [AppText.LoadFailed] = "Load failed: {0}",
        [AppText.AqnMissing] = "A matching AQN file was not found beside the AQP file.",
        [AppText.QualityMissing] = "file missing",
        [AppText.QualityHigh] = "high quality",
        [AppText.QualityNormal] = "normal quality",
        [AppText.UnnamedItem] = "Unnamed {0}",
        [AppText.RendererReady] = "OpenGL {0} ready",
        [AppText.RendererInitFailed] = "OpenGL {0} initialization failed: {1}",
        [AppText.RendererRenderFailed] = "OpenGL rendering failed: {0}",
        [AppText.RendererContextLost] = "The OpenGL context was lost.",
        [AppText.FailedWord] = "failed",
        [AppText.DataPathNotSelected] = "No game folder was selected.",
        [AppText.DataPathInvalid] = "The selected folder path cannot be used.",
        [AppText.DataPathFolderMissing] = "The selected folder does not exist: {0}",
        [AppText.DataPathStructureMissing] = "PSO2 data was not found. Select the game installation folder, pso2_bin, or pso2_bin\\data.",
        [AppText.DataPathFilesMissing] = "win32/win32reboot exists but contains no game data files. Check that installation or patching is complete.",
        [AppText.DataPathAccessDenied] = "The game data folder could not be accessed: {0}",
        [AppText.LanguageTip] = "Interface language",
        [AppText.RemoveModel] = "Remove model",
        [AppText.ModelRemoved] = "Removed model: {0}",
        [AppText.SkinTextures] = "Skin Textures",
        [AppText.SkinType1] = "Type 1",
        [AppText.SkinType2] = "Type 2",
        [AppText.SkinLoaded] = "Skin loaded: {0} · {1}x{2}",
        [AppText.SkinLoadFailed] = "Skin texture load failed: {0}",
        [AppText.ShapeUndone] = "Undid the last shape edit.",
        [AppText.ShapeRedone] = "Redid the shape edit.",
        [AppText.Options] = "Options…",
        [AppText.OptionsTitle] = "PSO2 Shape Studio Options",
        [AppText.General] = "General",
        [AppText.GameDataFolder] = "Game data folder",
        [AppText.Browse] = "Browse…",
        [AppText.DefaultSkinColors] = "Default skin colors",
        [AppText.MainSkinColor] = "Main skin",
        [AppText.SubSkinColor] = "Sub skin",
        [AppText.HexColorHelp] = "Enter an sRGB color as six hexadecimal digits (RRGGBB). These colors are used when no character file is loaded.",
        [AppText.EditableBones] = "Editable Bones",
        [AppText.BuiltInGroups] = "Built-in groups",
        [AppText.CustomGroups] = "Custom groups",
        [AppText.BoneEditorHelp] = "Enable or hide built-in sliders. Custom groups edit either one bone or a mirrored L/R pair.",
        [AppText.AddPair] = "Add L/R pair",
        [AppText.AddSingle] = "Add single bone",
        [AppText.Remove] = "Remove",
        [AppText.Pair] = "L/R pair",
        [AppText.Single] = "Single",
        [AppText.Kind] = "Type",
        [AppText.GroupName] = "Group name",
        [AppText.LeftBone] = "Left bone",
        [AppText.RightBone] = "Right bone",
        [AppText.BoneName] = "Bone name",
        [AppText.Save] = "Save",
        [AppText.Cancel] = "Cancel",
        [AppText.ModelRequiredForBone] = "Load a model with an AQN skeleton before adding editable bones.",
        [AppText.InvalidSkinColor] = "Enter both skin colors as six hexadecimal digits.",
        [AppText.MissingBoneFields] = "Each custom group needs a name and the required bone names.",
        [AppText.BoneNotFound] = "The loaded skeleton does not contain this bone: {0}",
        [AppText.DuplicateBone] = "Bone '{0}' is already assigned to another enabled group.",
        [AppText.OptionsSaved] = "Options saved.",
    };

    private static readonly IReadOnlyDictionary<AppText, string> Korean = new Dictionary<AppText, string>
    {
        [AppText.Subtitle] = "PSO2 AQP/AQN 모델과 체형 파일을 편집합니다",
        [AppText.OpenModels] = "모델 파일 열기…",
        [AppText.GameDataHeader] = "게임 데이터 / 모델 검색",
        [AppText.SelectGameFolder] = "게임 폴더 지정…",
        [AppText.RefreshCache] = "캐시 갱신",
        [AppText.DataFolderUnspecified] = "데이터 폴더 미지정",
        [AppText.DataFolderHelp] = "게임 설치 폴더, pso2_bin 또는 data 폴더를 선택하세요.",
        [AppText.SearchPlaceholder] = "이름 · ID · 파일명 · MD5",
        [AppText.Search] = "검색",
        [AppText.LoadSelectedModel] = "선택 모델 불러오기",
        [AppText.ShapeSliders] = "체형 슬라이더 · S / P / R",
        [AppText.LoadCharacter] = "캐릭터 파일 불러오기…",
        [AppText.LoadAqm] = "_sa.aqm 불러오기…",
        [AppText.ResetShape] = "체형 초기화",
        [AppText.SaveAqm] = "_sa.aqm 저장…",
        [AppText.CameraHelp] = "좌/우 드래그: 회전   Ctrl+드래그: 상하 이동   휠클릭: 시점 초기화   휠: 줌",
        [AppText.Ready] = "준비",
        [AppText.Statistics] = "모델 {0:N0} · 정점 {1:N0} · 삼각형 {2:N0} · 텍스처 {3:N0} · {4:F1} fps",
        [AppText.Scale] = "스케일 (S)",
        [AppText.Position] = "위치 (P)",
        [AppText.Rotation] = "회전 (R)",
        [AppText.ModelPickerTitle] = "PSO2 모델 파일 열기",
        [AppText.ModelPickerType] = "PSO2 모델 / 골격 / ICE",
        [AppText.GameFolderPickerTitle] = "PSO2 게임 설치 폴더 지정",
        [AppText.SearchResultCount] = "검색 결과 {0:N0}개",
        [AppText.ModelSearchFailed] = "모델 검색 실패: {0}",
        [AppText.WearBasewear] = "베이스웨어",
        [AppText.WearOuterwear] = "아웃터웨어",
        [AppText.WearSetwear] = "세트웨어",
        [AppText.WearCostume] = "코스튬(토탈)",
        [AppText.BackgroundTip] = "뷰포트 배경색",
        [AppText.FloorGuide] = "바닥 가이드",
        [AppText.FloorGuideTip] = "월드 Y=0 바닥 가이드 표시",
        [AppText.BackgroundDark] = "다크",
        [AppText.BackgroundGraphite] = "그라파이트",
        [AppText.BackgroundGray] = "그레이",
        [AppText.BackgroundSilver] = "실버",
        [AppText.BackgroundWhite] = "화이트",
        [AppText.BackgroundNavy] = "네이비",
        [AppText.BackgroundForest] = "포레스트",
        [AppText.BackgroundMagenta] = "마젠타",
        [AppText.DataPathValid] = "PSO2 게임 데이터 경로를 확인했습니다.",
        [AppText.CacheReadyInline] = "게임 데이터 확인됨 · 캐시 {0:N0}건 준비",
        [AppText.CacheReadyStatus] = "모델 캐시 {0:N0}건 준비",
        [AppText.DataPrepareFailedInline] = "게임 데이터 경로는 확인했지만 설정 또는 캐시를 준비하지 못했습니다: {0}",
        [AppText.DataPrepareFailedStatus] = "게임 데이터 준비 실패: {0}",
        [AppText.CacheUnavailable] = "캐시를 갱신할 수 없습니다: {0}",
        [AppText.Refreshing] = "갱신 중…",
        [AppText.CacheBuildingStatus] = "CMX 모델 캐시를 생성하는 중…",
        [AppText.CacheBuildingInline] = "게임 데이터 확인됨 · 모델 캐시를 갱신하는 중…",
        [AppText.CacheCompletedInline] = "게임 데이터 확인됨 · 캐시 {0:N0}건 · {1:F1}초",
        [AppText.CacheCreatedStatus] = "모델 캐시 {0:N0}건 생성 · {1:F1}초",
        [AppText.CacheFailedInline] = "게임 데이터는 확인했지만 캐시 갱신에 실패했습니다: {0}",
        [AppText.CacheFailedStatus] = "모델 캐시 생성 실패: {0}",
        [AppText.InvalidKeep] = "선택한 경로가 올바르지 않아 기존 경로를 유지합니다: {0}",
        [AppText.Invalid] = "경로가 올바르지 않습니다: {0}",
        [AppText.GameFolderFailed] = "게임 폴더 설정 실패: {0}",
        [AppText.RestoreFailed] = "저장된 데이터 폴더 복원 실패: {0}",
        [AppText.CharacterPickerTitle] = "PSO2 캐릭터 체형 불러오기",
        [AppText.CharacterPickerType] = "PSO2 캐릭터 파일",
        [AppText.AqmLoadTitle] = "Shape Adjust AQM 불러오기",
        [AppText.AqmFileType] = "AQM 모션",
        [AppText.AqmSaveTitle] = "Shape Adjust AQM 저장",
        [AppText.AqmSaved] = "{0} 저장 · {1:N0}개 본",
        [AppText.AqmSaveFailed] = "AQM 저장 실패: {0}",
        [AppText.ShapeReset] = "Shape Adjust를 초기화했습니다.",
        [AppText.ReadingFiles] = "파일을 읽는 중…",
        [AppText.ModelsCount] = "모델 {0:N0}개",
        [AppText.TexturesCount] = "표시 텍스처 {0:N0}장",
        [AppText.IceDdsCount] = "ICE DDS {0:N0}장",
        [AppText.IceEntriesCount] = "ICE 항목 {0:N0}개",
        [AppText.BonesCount] = "본 {0:N0}개",
        [AppText.CharacterBonesCount] = "캐릭터 본 {0:N0}개",
        [AppText.AqmAdjustmentsCount] = "AQM 조정 {0:N0}개",
        [AppText.NoLoadableData] = "로드할 데이터가 없습니다.",
        [AppText.LoadFailed] = "로드 실패: {0}",
        [AppText.AqnMissing] = "AQP 옆에서 같은 이름의 AQN을 찾지 못했습니다.",
        [AppText.QualityMissing] = "파일 없음",
        [AppText.QualityHigh] = "고품질",
        [AppText.QualityNormal] = "일반",
        [AppText.UnnamedItem] = "이름 없음 {0}",
        [AppText.RendererReady] = "OpenGL {0} 준비됨",
        [AppText.RendererInitFailed] = "OpenGL {0} 초기화 실패: {1}",
        [AppText.RendererRenderFailed] = "OpenGL 렌더 실패: {0}",
        [AppText.RendererContextLost] = "OpenGL 컨텍스트를 잃었습니다.",
        [AppText.FailedWord] = "실패",
        [AppText.DataPathNotSelected] = "게임 폴더가 선택되지 않았습니다.",
        [AppText.DataPathInvalid] = "사용할 수 없는 폴더 경로입니다.",
        [AppText.DataPathFolderMissing] = "선택한 폴더가 존재하지 않습니다: {0}",
        [AppText.DataPathStructureMissing] = "PSO2 데이터 폴더를 찾지 못했습니다. 게임 설치 폴더, pso2_bin 또는 pso2_bin\\data를 선택하세요.",
        [AppText.DataPathFilesMissing] = "win32/win32reboot 폴더는 있지만 실제 게임 데이터 파일이 없습니다. 설치 또는 패치가 완료됐는지 확인하세요.",
        [AppText.DataPathAccessDenied] = "게임 데이터 폴더에 접근할 수 없습니다: {0}",
        [AppText.LanguageTip] = "인터페이스 언어",
        [AppText.RemoveModel] = "모델 삭제",
        [AppText.ModelRemoved] = "모델 삭제: {0}",
        [AppText.SkinTextures] = "피부 텍스처",
        [AppText.SkinType1] = "타입 1",
        [AppText.SkinType2] = "타입 2",
        [AppText.SkinLoaded] = "피부 불러옴: {0} · {1}x{2}",
        [AppText.SkinLoadFailed] = "피부 텍스처 불러오기 실패: {0}",
        [AppText.ShapeUndone] = "마지막 체형 편집을 되돌렸습니다.",
        [AppText.ShapeRedone] = "체형 편집을 다시 적용했습니다.",
        [AppText.Options] = "옵션…",
        [AppText.OptionsTitle] = "PSO2 Shape Studio 옵션",
        [AppText.General] = "일반",
        [AppText.GameDataFolder] = "게임 데이터 폴더",
        [AppText.Browse] = "찾아보기…",
        [AppText.DefaultSkinColors] = "기본 피부색",
        [AppText.MainSkinColor] = "주 피부색",
        [AppText.SubSkinColor] = "보조 피부색",
        [AppText.HexColorHelp] = "sRGB 색상을 6자리 16진수(RRGGBB)로 입력하세요. 캐릭터 파일을 불러오지 않았을 때 적용됩니다.",
        [AppText.EditableBones] = "편집 가능한 본",
        [AppText.BuiltInGroups] = "기본 그룹",
        [AppText.CustomGroups] = "사용자 그룹",
        [AppText.BoneEditorHelp] = "기본 슬라이더를 표시하거나 숨기고, 단일 본 또는 좌우 대칭 L/R 묶음을 추가할 수 있습니다.",
        [AppText.AddPair] = "L/R 묶음 추가",
        [AppText.AddSingle] = "단일 본 추가",
        [AppText.Remove] = "삭제",
        [AppText.Pair] = "L/R 묶음",
        [AppText.Single] = "단일",
        [AppText.Kind] = "종류",
        [AppText.GroupName] = "그룹 이름",
        [AppText.LeftBone] = "왼쪽 본",
        [AppText.RightBone] = "오른쪽 본",
        [AppText.BoneName] = "본 이름",
        [AppText.Save] = "저장",
        [AppText.Cancel] = "취소",
        [AppText.ModelRequiredForBone] = "편집할 본을 추가하려면 AQN 스켈레톤이 포함된 모델을 먼저 불러오세요.",
        [AppText.InvalidSkinColor] = "두 피부색을 모두 6자리 16진수로 입력하세요.",
        [AppText.MissingBoneFields] = "사용자 그룹에는 그룹 이름과 필요한 본 이름을 모두 입력해야 합니다.",
        [AppText.BoneNotFound] = "현재 스켈레톤에 없는 본입니다: {0}",
        [AppText.DuplicateBone] = "본 '{0}'은(는) 이미 다른 활성 그룹에 지정되어 있습니다.",
        [AppText.OptionsSaved] = "옵션을 저장했습니다.",
    };

    private static readonly IReadOnlyDictionary<AppText, string> Japanese = new Dictionary<AppText, string>
    {
        [AppText.Subtitle] = "PSO2のAQP/AQNモデルと体型ファイルを編集します",
        [AppText.OpenModels] = "モデルファイルを開く…",
        [AppText.GameDataHeader] = "ゲームデータ / モデル検索",
        [AppText.SelectGameFolder] = "ゲームフォルダーを選択…",
        [AppText.RefreshCache] = "キャッシュ更新",
        [AppText.DataFolderUnspecified] = "データフォルダー未選択",
        [AppText.DataFolderHelp] = "ゲームのインストール先、pso2_bin、またはdataフォルダーを選択してください。",
        [AppText.SearchPlaceholder] = "名前 · ID · ファイル名 · MD5",
        [AppText.Search] = "検索",
        [AppText.LoadSelectedModel] = "選択したモデルを読み込む",
        [AppText.ShapeSliders] = "体型スライダー · S / P / R",
        [AppText.LoadCharacter] = "キャラクターファイルを開く…",
        [AppText.LoadAqm] = "_sa.aqmを開く…",
        [AppText.ResetShape] = "体型をリセット",
        [AppText.SaveAqm] = "_sa.aqmを保存…",
        [AppText.CameraHelp] = "左右ドラッグ：回転   Ctrl+ドラッグ：上下移動   中クリック：視点リセット   ホイール：ズーム",
        [AppText.Ready] = "準備完了",
        [AppText.Statistics] = "モデル {0:N0} · 頂点 {1:N0} · 三角形 {2:N0} · テクスチャ {3:N0} · {4:F1} fps",
        [AppText.Scale] = "スケール (S)",
        [AppText.Position] = "位置 (P)",
        [AppText.Rotation] = "回転 (R)",
        [AppText.ModelPickerTitle] = "PSO2モデルファイルを開く",
        [AppText.ModelPickerType] = "PSO2モデル / スケルトン / ICE",
        [AppText.GameFolderPickerTitle] = "PSO2ゲームのインストール先を選択",
        [AppText.SearchResultCount] = "検索結果 {0:N0}件",
        [AppText.ModelSearchFailed] = "モデル検索に失敗しました：{0}",
        [AppText.WearBasewear] = "ベースウェア",
        [AppText.WearOuterwear] = "アウターウェア",
        [AppText.WearSetwear] = "セットウェア",
        [AppText.WearCostume] = "コスチューム",
        [AppText.BackgroundTip] = "ビューポート背景色",
        [AppText.FloorGuide] = "床ガイド",
        [AppText.FloorGuideTip] = "ワールドY=0の床ガイドを表示",
        [AppText.BackgroundDark] = "ダーク",
        [AppText.BackgroundGraphite] = "グラファイト",
        [AppText.BackgroundGray] = "グレー",
        [AppText.BackgroundSilver] = "シルバー",
        [AppText.BackgroundWhite] = "ホワイト",
        [AppText.BackgroundNavy] = "ネイビー",
        [AppText.BackgroundForest] = "フォレスト",
        [AppText.BackgroundMagenta] = "マゼンタ",
        [AppText.DataPathValid] = "PSO2ゲームデータを確認しました。",
        [AppText.CacheReadyInline] = "ゲームデータ確認済み · キャッシュ {0:N0}件",
        [AppText.CacheReadyStatus] = "モデルキャッシュ {0:N0}件を準備しました",
        [AppText.DataPrepareFailedInline] = "ゲームデータは確認できましたが、設定またはキャッシュの準備に失敗しました：{0}",
        [AppText.DataPrepareFailedStatus] = "ゲームデータの準備に失敗しました：{0}",
        [AppText.CacheUnavailable] = "キャッシュを更新できません：{0}",
        [AppText.Refreshing] = "更新中…",
        [AppText.CacheBuildingStatus] = "CMXモデルキャッシュを作成中…",
        [AppText.CacheBuildingInline] = "ゲームデータ確認済み · モデルキャッシュを更新中…",
        [AppText.CacheCompletedInline] = "ゲームデータ確認済み · キャッシュ {0:N0}件 · {1:F1}秒",
        [AppText.CacheCreatedStatus] = "モデルキャッシュ {0:N0}件を作成 · {1:F1}秒",
        [AppText.CacheFailedInline] = "ゲームデータは確認できましたが、キャッシュ更新に失敗しました：{0}",
        [AppText.CacheFailedStatus] = "モデルキャッシュの作成に失敗しました：{0}",
        [AppText.InvalidKeep] = "選択したパスが正しくないため、現在のパスを維持します：{0}",
        [AppText.Invalid] = "選択したパスが正しくありません：{0}",
        [AppText.GameFolderFailed] = "ゲームフォルダーの設定に失敗しました：{0}",
        [AppText.RestoreFailed] = "保存されたデータフォルダーの復元に失敗しました：{0}",
        [AppText.CharacterPickerTitle] = "PSO2キャラクター体型ファイルを開く",
        [AppText.CharacterPickerType] = "PSO2キャラクターファイル",
        [AppText.AqmLoadTitle] = "Shape Adjust AQMを開く",
        [AppText.AqmFileType] = "AQMモーション",
        [AppText.AqmSaveTitle] = "Shape Adjust AQMを保存",
        [AppText.AqmSaved] = "{0}を保存 · 調整ボーン {1:N0}個",
        [AppText.AqmSaveFailed] = "AQMの保存に失敗しました：{0}",
        [AppText.ShapeReset] = "Shape Adjustをリセットしました。",
        [AppText.ReadingFiles] = "ファイルを読み込み中…",
        [AppText.ModelsCount] = "モデル {0:N0}個",
        [AppText.TexturesCount] = "表示テクスチャ {0:N0}枚",
        [AppText.IceDdsCount] = "ICE DDS {0:N0}枚",
        [AppText.IceEntriesCount] = "ICE項目 {0:N0}件",
        [AppText.BonesCount] = "ボーン {0:N0}本",
        [AppText.CharacterBonesCount] = "キャラクターボーン {0:N0}本",
        [AppText.AqmAdjustmentsCount] = "AQM調整 {0:N0}件",
        [AppText.NoLoadableData] = "読み込み可能なデータがありません。",
        [AppText.LoadFailed] = "読み込みに失敗しました：{0}",
        [AppText.AqnMissing] = "AQPと同名のAQNファイルが見つかりません。",
        [AppText.QualityMissing] = "ファイルなし",
        [AppText.QualityHigh] = "高品質",
        [AppText.QualityNormal] = "通常",
        [AppText.UnnamedItem] = "名称不明 {0}",
        [AppText.RendererReady] = "OpenGL {0} 準備完了",
        [AppText.RendererInitFailed] = "OpenGL {0} の初期化に失敗しました：{1}",
        [AppText.RendererRenderFailed] = "OpenGL描画に失敗しました：{0}",
        [AppText.RendererContextLost] = "OpenGLコンテキストが失われました。",
        [AppText.FailedWord] = "失敗",
        [AppText.DataPathNotSelected] = "ゲームフォルダーが選択されていません。",
        [AppText.DataPathInvalid] = "選択したフォルダーパスは使用できません。",
        [AppText.DataPathFolderMissing] = "選択したフォルダーが存在しません：{0}",
        [AppText.DataPathStructureMissing] = "PSO2データが見つかりません。ゲームのインストール先、pso2_bin、またはpso2_bin\\dataを選択してください。",
        [AppText.DataPathFilesMissing] = "win32/win32rebootはありますが、ゲームデータファイルがありません。インストールまたはパッチの完了を確認してください。",
        [AppText.DataPathAccessDenied] = "ゲームデータフォルダーにアクセスできません：{0}",
        [AppText.LanguageTip] = "表示言語",
        [AppText.RemoveModel] = "モデルを削除",
        [AppText.ModelRemoved] = "モデルを削除しました：{0}",
        [AppText.SkinTextures] = "スキンテクスチャ",
        [AppText.SkinType1] = "タイプ1",
        [AppText.SkinType2] = "タイプ2",
        [AppText.SkinLoaded] = "スキンを読み込みました：{0} · {1}x{2}",
        [AppText.SkinLoadFailed] = "スキンテクスチャの読み込みに失敗しました：{0}",
        [AppText.ShapeUndone] = "直前の体型編集を元に戻しました。",
        [AppText.ShapeRedone] = "体型編集をやり直しました。",
        [AppText.Options] = "オプション…",
        [AppText.OptionsTitle] = "PSO2 Shape Studio オプション",
        [AppText.General] = "一般",
        [AppText.GameDataFolder] = "ゲームデータフォルダー",
        [AppText.Browse] = "参照…",
        [AppText.DefaultSkinColors] = "デフォルトの肌カラー",
        [AppText.MainSkinColor] = "メイン肌カラー",
        [AppText.SubSkinColor] = "サブ肌カラー",
        [AppText.HexColorHelp] = "sRGBカラーを6桁の16進数（RRGGBB）で入力します。キャラクターファイル未読込時に使用されます。",
        [AppText.EditableBones] = "編集可能なボーン",
        [AppText.BuiltInGroups] = "標準グループ",
        [AppText.CustomGroups] = "カスタムグループ",
        [AppText.BoneEditorHelp] = "標準スライダーの表示を切り替え、単一ボーンまたは左右対称のL/Rペアを追加できます。",
        [AppText.AddPair] = "L/Rペアを追加",
        [AppText.AddSingle] = "単一ボーンを追加",
        [AppText.Remove] = "削除",
        [AppText.Pair] = "L/Rペア",
        [AppText.Single] = "単一",
        [AppText.Kind] = "種類",
        [AppText.GroupName] = "グループ名",
        [AppText.LeftBone] = "左ボーン",
        [AppText.RightBone] = "右ボーン",
        [AppText.BoneName] = "ボーン名",
        [AppText.Save] = "保存",
        [AppText.Cancel] = "キャンセル",
        [AppText.ModelRequiredForBone] = "編集ボーンを追加するには、AQNスケルトンを含むモデルを先に読み込んでください。",
        [AppText.InvalidSkinColor] = "肌カラーを両方とも6桁の16進数で入力してください。",
        [AppText.MissingBoneFields] = "カスタムグループにはグループ名と必要なボーン名を入力してください。",
        [AppText.BoneNotFound] = "現在のスケルトンに存在しないボーンです：{0}",
        [AppText.DuplicateBone] = "ボーン「{0}」は別の有効なグループに割り当て済みです。",
        [AppText.OptionsSaved] = "オプションを保存しました。",
    };

    private static readonly IReadOnlyDictionary<string, (string English, string Korean, string Japanese)>
        ShapeNames = new Dictionary<string, (string, string, string)>(StringComparer.OrdinalIgnoreCase)
        {
            ["bodyroot"] = ("Sole Height (body_root Y)", "발바닥 높이 (body_root Y)", "足裏の高さ (body_root Y)"),
            ["breast"] = ("Breast", "가슴", "胸"),
            ["breast2"] = ("Breast Scale", "가슴 스케일", "胸スケール"),
            ["cbreast2"] = ("Center Breast Scale", "중앙 가슴 스케일", "中央胸スケール"),
            ["clav"] = ("Clavicle", "쇄골", "鎖骨"),
            ["waist"] = ("Waist", "허리", "ウエスト"),
            ["hip"] = ("Hip", "엉덩이", "ヒップ"),
            ["pelvis"] = ("Pelvis", "골반", "骨盤"),
            ["hiptw"] = ("Hip Twist", "엉덩이 비틀기", "ヒップツイスト"),
            ["thigh"] = ("Thigh", "허벅지", "太もも"),
            ["thightw"] = ("Thigh Twist", "허벅지 비틀기", "太ももツイスト"),
            ["thightw2"] = ("Thigh Twist 2", "허벅지 비틀기 2", "太ももツイスト2"),
            ["calf0"] = ("Calf Upper", "종아리 위쪽", "ふくらはぎ上部"),
            ["calf"] = ("Calf", "종아리", "ふくらはぎ"),
            ["foot"] = ("Foot", "발", "足"),
        };

    private static readonly IReadOnlyDictionary<string, (string English, string Korean, string Japanese)>
        ObjectTypes = new Dictionary<string, (string, string, string)>(StringComparer.OrdinalIgnoreCase)
        {
            ["accessory"] = ("Accessory", "액세서리", "アクセサリー"),
            ["basewear"] = ("Basewear / Setwear", "베이스웨어 / 세트웨어", "ベースウェア / セットウェア"),
            ["costume"] = ("Costume", "코스튬", "コスチューム"),
            ["cast_body"] = ("CAST Body", "캐스트 바디", "キャストボディ"),
            ["bodypaint"] = ("Body Paint", "바디 페인트", "ボディペイント"),
            ["cast_arms"] = ("CAST Arms", "캐스트 암", "キャストアーム"),
            ["cast_legs"] = ("CAST Legs", "캐스트 레그", "キャストレッグ"),
            ["ear"] = ("Ears", "귀", "耳"),
            ["eye"] = ("Eyes", "눈", "瞳"),
            ["eyebrow"] = ("Eyebrows", "눈썹", "まゆ"),
            ["eyelash"] = ("Eyelashes", "속눈썹", "まつげ"),
            ["face"] = ("Face", "얼굴", "顔"),
            ["face_texture"] = ("Face Type", "얼굴형", "顔タイプ"),
            ["facepaint"] = ("Face Paint", "페이스 페인트", "フェイスペイント"),
            ["hair"] = ("Hair", "헤어", "ヘア"),
            ["horn"] = ("Horns", "뿔", "角"),
            ["innerwear"] = ("Innerwear", "이너웨어", "インナーウェア"),
            ["outerwear"] = ("Outerwear", "아우터웨어", "アウターウェア"),
            ["skin"] = ("Skin", "스킨", "スキン"),
            ["sticker"] = ("Sticker", "스티커", "ステッカー"),
            ["teeth"] = ("Teeth", "치아", "歯"),
        };

    public static string LanguageCode(AppLanguage language) => language switch
    {
        AppLanguage.Korean => "ko",
        AppLanguage.Japanese => "ja",
        _ => "en",
    };

    public static AppLanguage ParseLanguage(string? code) => code?.ToLowerInvariant() switch
    {
        "ko" or "kr" or "korean" => AppLanguage.Korean,
        "ja" or "jp" or "japanese" => AppLanguage.Japanese,
        _ => AppLanguage.English,
    };

    public static string Text(AppLanguage language, AppText key, params object?[] arguments)
    {
        var localized = language switch
        {
            AppLanguage.Korean when Korean.TryGetValue(key, out var value) => value,
            AppLanguage.Japanese when Japanese.TryGetValue(key, out var value) => value,
            _ => English[key],
        };
        return arguments.Length == 0
            ? localized
            : string.Format(Culture(language), localized, arguments);
    }

    public static string ShapeName(AppLanguage language, string key, string fallback)
    {
        if (!ShapeNames.TryGetValue(key, out var names))
        {
            return fallback;
        }

        return language switch
        {
            AppLanguage.Korean => names.Korean,
            AppLanguage.Japanese => names.Japanese,
            _ => names.English,
        };
    }

    public static string ObjectTypeName(AppLanguage language, string objectType)
    {
        if (!ObjectTypes.TryGetValue(objectType, out var names))
        {
            return objectType;
        }

        return language switch
        {
            AppLanguage.Korean => names.Korean,
            AppLanguage.Japanese => names.Japanese,
            _ => names.English,
        };
    }

    public static string DataPathError(AppLanguage language, Pso2DataPathValidation validation) =>
        validation.Error switch
        {
            Pso2DataPathError.NotSelected => Text(language, AppText.DataPathNotSelected),
            Pso2DataPathError.InvalidPath => Text(language, AppText.DataPathInvalid),
            Pso2DataPathError.FolderNotFound => Text(
                language, AppText.DataPathFolderMissing, validation.SelectedPath),
            Pso2DataPathError.DataStructureNotFound => Text(language, AppText.DataPathStructureMissing),
            Pso2DataPathError.GameFilesNotFound => Text(language, AppText.DataPathFilesMissing),
            Pso2DataPathError.AccessDenied => Text(
                language, AppText.DataPathAccessDenied, validation.DataPath ?? validation.SelectedPath),
            _ => validation.Message,
        };

    private static CultureInfo Culture(AppLanguage language) => language switch
    {
        AppLanguage.Korean => CultureInfo.GetCultureInfo("ko-KR"),
        AppLanguage.Japanese => CultureInfo.GetCultureInfo("ja-JP"),
        _ => CultureInfo.GetCultureInfo("en-US"),
    };
}
